import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

/// Ejemplo de recetas locales para migrar a Firestore
final List<Map<String, dynamic>> localRecipes = [
  {
    'name': 'Tostadas con palta y huevo',
    'calories': '350',
    'time': '10 min',
    'image': 'assets/images/avocado_toast.jpg',
    'difficulty': 'Fácil',
    'types': ['Desayunos', 'Cenas'],
    'ingredients': [
      '2 rebanadas de pan integral',
      '1 palta madura',
      '2 huevos',
      'Sal y pimienta al gusto',
    ],
    'instructions': [
      'Tostar el pan.',
      'Aplastar la palta y untar sobre el pan.',
      'Cocinar los huevos al gusto y colocar sobre la palta.',
      'Salpimentar y servir.',
    ],
    'nutrition': {
      'protein': '14g',
      'carbs': '32g',
      'fat': '18g',
      'fiber': '7g',
    },
  },
{
  'name': 'Ensalada de Quinoa con Pollo',
  'calories': '420',
  'time': '25 min',
  'image': 'https://cdn.pixabay.com/photo/2017/06/02/18/24/quinoa-2369270_1280.jpg',
  'difficulty': 'Media',
  'types': ['Almuerzos', 'Cenas'],
  'ingredients': [
    '100g de pechuga de pollo',
    '1/2 taza de quinoa cocida',
    '1/4 palta picada',
    'Tomates cherry',
    'Hojas verdes',
    'Aceite de oliva, sal y limón',
  ],
  'instructions': [
    'Cocinar la pechuga de pollo y cortar en cubos.',
    'Mezclar con la quinoa, palta, tomates y hojas verdes.',
    'Aliñar con aceite de oliva, sal y limón.',
    'Servir fría.',
  ],
  'nutrition': {
    'protein': '35g',
    'carbs': '30g',
    'fat': '18g',
    'fiber': '5g',
  },
},
{
  'name': 'Pasta Integral con Salsa de Tomate y Atún',
  'calories': '480',
  'time': '20 min',
  'image': 'https://cdn.pixabay.com/photo/2017/06/02/18/24/pasta-2369287_1280.jpg',
  'difficulty': 'Fácil',
  'types': ['Almuerzos'],
  'ingredients': [
    '80g de pasta integral',
    '1 lata de atún al agua',
    '1/2 taza de salsa de tomate natural',
    'Orégano, sal y pimienta',
  ],
  'instructions': [
    'Cocinar la pasta según las instrucciones.',
    'Calentar la salsa con el atún y los condimentos.',
    'Mezclar con la pasta cocida.',
    'Servir caliente.',
  ],
  'nutrition': {
    'protein': '28g',
    'carbs': '55g',
    'fat': '12g',
    'fiber': '8g',
  },
},
{
  'name': 'Avena con Frutas y Semillas',
  'calories': '320',
  'time': '8 min',
  'image': 'https://cdn.pixabay.com/photo/2020/01/24/16/47/oatmeal-4786465_1280.jpg',
  'difficulty': 'Fácil',
  'types': ['Desayunos'],
  'ingredients': [
    '1/2 taza de avena',
    '1 taza de leche o bebida vegetal',
    '1/2 plátano en rodajas',
    'Frutillas o arándanos',
    '1 cda de semillas (chia o linaza)',
  ],
  'instructions': [
    'Calentar la avena con leche por 5 minutos.',
    'Servir en un bol y añadir frutas y semillas por encima.',
    'Opcional: endulzar con miel.',
  ],
  'nutrition': {
    'protein': '9g',
    'carbs': '40g',
    'fat': '9g',
    'fiber': '6g',
  },
},
{
  'name': 'Salteado de Verduras con Tofu',
  'calories': '310',
  'time': '15 min',
  'image': 'https://cdn.pixabay.com/photo/2020/01/02/17/41/vegan-4736797_1280.jpg',
  'difficulty': 'Media',
  'types': ['Almuerzos', 'Cenas'],
  'ingredients': [
    '100g de tofu firme',
    '1/2 pimentón en tiras',
    '1 zanahoria rallada',
    '1/2 zapallo italiano en cubos',
    'Salsa de soya baja en sodio',
    'Aceite de oliva',
  ],
  'instructions': [
    'Cortar el tofu en cubos y dorar en sartén con aceite de oliva.',
    'Agregar las verduras y saltear por 5-7 minutos.',
    'Añadir salsa de soya al gusto y servir caliente.',
  ],
  'nutrition': {
    'protein': '17g',
    'carbs': '20g',
    'fat': '18g',
    'fiber': '5g',
  },
},
{
  'name': 'Wrap de Pollo con Verduras',
  'calories': '390',
  'time': '15 min',
  'image': 'https://cdn.pixabay.com/photo/2017/01/19/15/40/wrap-1991782_1280.jpg',
  'difficulty': 'Fácil',
  'types': ['Almuerzos', 'Cenas'],
  'ingredients': [
    '1 tortilla integral',
    '100g de pechuga de pollo cocido',
    'Hojas de lechuga',
    'Tiras de zanahoria y pepino',
    '1 cda de yogur natural',
  ],
  'instructions': [
    'Calentar la tortilla.',
    'Agregar pollo y verduras.',
    'Añadir yogur como aderezo.',
    'Enrollar y servir.',
  ],
  'nutrition': {
    'protein': '30g',
    'carbs': '28g',
    'fat': '14g',
    'fiber': '4g',
  },
},
{
  'name': 'Omelette de Claras con Espinaca',
  'calories': '180',
  'time': '10 min',
  'image': 'https://cdn.pixabay.com/photo/2023/07/09/13/47/omelet-8114692_1280.jpg',
  'difficulty': 'Fácil',
  'types': ['Desayunos', 'Cenas'],
  'ingredients': [
    '4 claras de huevo',
    '1 taza de espinaca fresca',
    '1/4 cebolla picada',
    'Sal, pimienta y orégano',
    '1 cdta de aceite de oliva',
  ],
  'instructions': [
    'Saltear la cebolla y espinaca con un poco de aceite.',
    'Batir las claras y verter en sartén caliente.',
    'Agregar las verduras, doblar el omelette y cocinar 2-3 minutos.',
    'Servir caliente.',
  ],
  'nutrition': {
    'protein': '18g',
    'carbs': '4g',
    'fat': '7g',
    'fiber': '2g',
  },
},
{
  'name': 'Salteado de Tofu y Verduras',
  'calories': '350',
  'time': '20 min',
  'image': 'https://cdn.pixabay.com/photo/2017/03/06/21/00/tofu-2129873_1280.jpg',
  'difficulty': 'Media',
  'types': ['Almuerzos', 'Cenas', 'Vegetariano'],
  'ingredients': [
    '150g de tofu firme',
    'Brócoli, zanahoria, pimiento',
    '1 cda de aceite de oliva',
    'Salsa de soya baja en sodio',
    'Ajo y jengibre al gusto',
  ],
  'instructions': [
    'Cortar tofu en cubos y dorar en aceite.',
    'Agregar las verduras y saltear 5–8 minutos.',
    'Incorporar salsa de soya, ajo y jengibre.',
    'Servir caliente.',
  ],
  'nutrition': {
    'protein': '20g',
    'carbs': '22g',
    'fat': '20g',
    'fiber': '6g',
  },
},
{
  'name': 'Guiso de Lentejas Casero',
  'calories': '390',
  'time': '30 min',
  'image': 'https://cdn.pixabay.com/photo/2016/11/21/16/11/lentils-1845939_1280.jpg',
  'difficulty': 'Fácil',
  'types': ['Almuerzos'],
  'ingredients': [
    '1 taza de lentejas cocidas',
    '1 zanahoria picada',
    '1/2 cebolla',
    '1 diente de ajo',
    '1 tomate',
    '1/2 cdta de comino',
    'Sal, pimienta y aceite de oliva',
  ],
  'instructions': [
    'Sofreír cebolla, ajo y zanahoria con aceite.',
    'Agregar el tomate picado y cocinar hasta que se deshaga.',
    'Añadir lentejas cocidas, condimentos y 1 taza de agua.',
    'Hervir por 10 minutos y servir.',
  ],
  'nutrition': {
    'protein': '22g',
    'carbs': '50g',
    'fat': '8g',
    'fiber': '15g',
  },
},
{
  'name': 'Smoothie de Plátano y Mantequilla de Maní',
  'calories': '300',
  'time': '5 min',
  'image': 'https://cdn.pixabay.com/photo/2017/07/16/10/43/smoothies-2500166_1280.jpg',
  'difficulty': 'Fácil',
  'types': ['Desayunos', 'Snacks'],
  'ingredients': [
    '1 plátano',
    '1 taza de leche o bebida vegetal',
    '1 cda de mantequilla de maní natural',
    'Hielo (opcional)',
    'Canela al gusto',
  ],
  'instructions': [
    'Agregar todos los ingredientes a la licuadora.',
    'Licuar hasta que quede suave.',
    'Servir frío con un poco de canela encima.',
  ],
  'nutrition': {
    'protein': '10g',
    'carbs': '28g',
    'fat': '15g',
    'fiber': '4g',
  },
},
{
  'name': 'Camote Asado con Garbanzos y Yogur',
  'calories': '430',
  'time': '35 min',
  'image': 'https://cdn.pixabay.com/photo/2018/06/30/12/35/sweet-potato-3500580_1280.jpg',
  'difficulty': 'Media',
  'types': ['Almuerzos', 'Cenas'],
  'ingredients': [
    '1 camote mediano',
    '1/2 taza de garbanzos cocidos',
    '1/4 taza de yogur natural',
    'Jugo de limón',
    'Aceite de oliva, sal, comino y paprika',
  ],
  'instructions': [
    'Hornear el camote entero por 30 minutos a 200°C.',
    'Dorar garbanzos con aceite y especias en sartén.',
    'Abrir el camote y agregar los garbanzos por encima.',
    'Agregar yogur y unas gotas de limón antes de servir.',
  ],
  'nutrition': {
    'protein': '14g',
    'carbs': '60g',
    'fat': '12g',
    'fiber': '10g',
  },
},
{
  'name': 'Salmón a la Plancha con Brócoli y Limón',
  'calories': '450',
  'time': '20 min',
  'image': 'https://cdn.pixabay.com/photo/2017/07/16/10/43/salmon-2505037_1280.jpg',
  'difficulty': 'Fácil',
  'types': ['Almuerzos', 'Cenas'],
  'ingredients': [
    '150g de salmón',
    '1 taza de brócoli al vapor',
    '1 cda de aceite de oliva',
    'Limón, sal y pimienta',
  ],
  'instructions': [
    'Sazonar el salmón con sal, pimienta y jugo de limón.',
    'Cocinar en sartén caliente con aceite 4-5 min por lado.',
    'Servir con brócoli al vapor y un chorrito de limón.',
  ],
  'nutrition': {
    'protein': '35g',
    'carbs': '10g',
    'fat': '30g',
    'fiber': '4g',
  },
},
{
  'name': 'Bolitas Energéticas de Avena y Cacao',
  'calories': '120 por bolita',
  'time': '10 min (más reposo)',
  'image': 'https://cdn.pixabay.com/photo/2019/01/14/20/02/oatmeal-3938211_1280.jpg',
  'difficulty': 'Fácil',
  'types': ['Snacks', 'Postres saludables'],
  'ingredients': [
    '1 taza de avena',
    '1/3 taza de mantequilla de maní natural',
    '2 cdas de cacao en polvo sin azúcar',
    '2 cdas de miel o sirope',
    '1 cda de semillas de chía (opcional)',
  ],
  'instructions': [
    'Mezclar todos los ingredientes en un bowl.',
    'Formar bolitas con las manos.',
    'Refrigerar por al menos 30 minutos antes de comer.',
  ],
  'nutrition': {
    'protein': '4g',
    'carbs': '12g',
    'fat': '6g',
    'fiber': '2g',
  },
},
{
  'name': 'Ensalada Fría de Cous Cous con Pollo',
  'calories': '460',
  'time': '20 min',
  'image': 'https://cdn.pixabay.com/photo/2015/04/08/13/13/couscous-712661_1280.jpg',
  'difficulty': 'Fácil',
  'types': ['Almuerzos', 'Para llevar'],
  'ingredients': [
    '1/2 taza de cous cous cocido',
    '100g de pechuga de pollo cocido en cubos',
    '1/4 pepino picado',
    '1/4 taza de perejil picado',
    'Jugo de limón, sal, aceite de oliva',
  ],
  'instructions': [
    'Preparar el cous cous con agua caliente y dejar enfriar.',
    'Mezclar con pollo, pepino y perejil.',
    'Aliñar con jugo de limón, sal y aceite.',
    'Enfriar en un tupper y llevar al trabajo o universidad.',
  ],
  'nutrition': {
    'protein': '30g',
    'carbs': '35g',
    'fat': '18g',
    'fiber': '4g',
  },
},
{
  'name': 'Yogur Griego con Proteína y Frutas',
  'calories': '250',
  'time': '5 min',
  'image': 'https://cdn.pixabay.com/photo/2021/10/25/14/46/yogurt-6740996_1280.jpg',
  'difficulty': 'Fácil',
  'types': ['Snacks', 'Meriendas', 'Postres'],
  'ingredients': [
    '1 taza de yogur griego natural sin azúcar',
    '1 scoop de proteína en polvo (vainilla o neutra)',
    '1/2 plátano en rodajas',
    'Frambuesas o arándanos',
    'Canela (opcional)',
  ],
  'instructions': [
    'Mezclar el yogur con la proteína en polvo.',
    'Agregar la fruta por encima y espolvorear canela.',
    'Ideal para después del entrenamiento o como snack.',
  ],
  'nutrition': {
    'protein': '30g',
    'carbs': '15g',
    'fat': '6g',
    'fiber': '2g',
  },
},
{
  'name': 'Mousse de Frutilla sin Azúcar',
  'calories': '140',
  'time': '15 min + refrigeración',
  'image': 'https://cdn.pixabay.com/photo/2023/03/06/10/31/mousse-7832047_1280.jpg',
  'difficulty': 'Media',
  'types': ['Postres'],
  'ingredients': [
    '1 taza de frutillas frescas',
    '1/2 taza de yogur griego natural',
    '1 cda de gelatina sin sabor hidratada',
    'Endulzante natural al gusto (como stevia)',
  ],
  'instructions': [
    'Licuar las frutillas con el yogur y endulzante.',
    'Agregar la gelatina disuelta en caliente y mezclar.',
    'Verter en vasitos y refrigerar por 2 horas.',
    'Servir frío como postre saludable.',
  ],
  'nutrition': {
    'protein': '9g',
    'carbs': '10g',
    'fat': '5g',
    'fiber': '2g',
  },
},
{
  'name': 'Muffins de Plátano y Avena',
  'calories': '160 por unidad',
  'time': '25 min',
  'image': 'https://cdn.pixabay.com/photo/2018/03/16/17/37/muffin-3220561_1280.jpg',
  'difficulty': 'Fácil',
  'types': ['Desayunos', 'Snacks', 'Niños'],
  'ingredients': [
    '2 plátanos maduros',
    '1 taza de avena molida',
    '2 huevos',
    '1 cdita de canela',
    '1/2 cdita de polvo de hornear',
    'Opcional: chips de chocolate oscuro sin azúcar',
  ],
  'instructions': [
    'Precalentar el horno a 180°C.',
    'Mezclar todos los ingredientes hasta obtener una masa homogénea.',
    'Verter en moldes para muffins.',
    'Hornear por 20-22 minutos.',
  ],
  'nutrition': {
    'protein': '5g',
    'carbs': '20g',
    'fat': '6g',
    'fiber': '3g',
  },
},
{
  'name': 'Ensalada de Quínoa y Palta',
  'calories': '360',
  'time': '15 min',
  'image': 'https://cdn.pixabay.com/photo/2020/04/09/08/46/quinoa-5018756_1280.jpg',
  'difficulty': 'Fácil',
  'types': ['Almuerzos', 'Diabéticos'],
  'ingredients': [
    '1/2 taza de quínoa cocida',
    '1/2 palta',
    '1/4 taza de tomate cherry',
    'Hojas verdes (rúcula o espinaca)',
    'Jugo de limón, aceite de oliva, sal y pimienta',
  ],
  'instructions': [
    'Enfriar la quínoa cocida.',
    'Mezclar con los demás ingredientes.',
    'Aliñar con limón y aceite de oliva.',
  ],
  'nutrition': {
    'protein': '9g',
    'carbs': '30g',
    'fat': '20g',
    'fiber': '7g',
  },
},
{
  'name': 'Wrap Vegano de Hummus y Vegetales',
  'calories': '330',
  'time': '10 min',
  'image': 'https://cdn.pixabay.com/photo/2021/06/18/17/47/wrap-6346393_1280.jpg',
  'difficulty': 'Fácil',
  'types': ['Almuerzos', 'Cenas', 'Veganos'],
  'ingredients': [
    '1 tortilla integral',
    '2 cdas de hummus',
    '1/4 taza de zanahoria rallada',
    '1/4 palta en láminas',
    'Espinaca o lechuga',
    'Pepino en tiras',
  ],
  'instructions': [
    'Untar la tortilla con hummus.',
    'Agregar las verduras en el centro.',
    'Enrollar y servir frío o tibio.',
  ],
  'nutrition': {
    'protein': '8g',
    'carbs': '28g',
    'fat': '15g',
    'fiber': '8g',
  },
},
{
  'name': 'Omelette de Claras con Verduras',
  'calories': '200',
  'time': '10 min',
  'image': 'https://cdn.pixabay.com/photo/2017/03/14/16/40/omelet-2147382_1280.jpg',
  'difficulty': 'Fácil',
  'types': ['Cenas', 'Desayunos'],
  'ingredients': [
    '4 claras de huevo',
    '1/4 taza de champiñones picados',
    '1/4 taza de espinacas',
    '1 cdita de aceite de oliva',
    'Sal y pimienta al gusto',
  ],
  'instructions': [
    'Saltear los vegetales en aceite por 2-3 minutos.',
    'Agregar las claras batidas y cocinar hasta cuajar.',
    'Doblar como omelette y servir caliente.',
  ],
  'nutrition': {
    'protein': '18g',
    'carbs': '4g',
    'fat': '7g',
    'fiber': '2g',
  },
},
{
  'name': 'Bowl de Pollo Thai sin Gluten',
  'calories': '480',
  'time': '25 min',
  'image': 'https://cdn.pixabay.com/photo/2020/10/26/11/21/asian-food-5687679_1280.jpg',
  'difficulty': 'Media',
  'types': ['Almuerzos', 'Sin gluten'],
  'ingredients': [
    '100g de pechuga de pollo en tiras',
    '1/2 taza de arroz jazmín o integral',
    '1/4 taza de zanahoria rallada',
    '1/4 taza de repollo morado',
    'Salsa de soya sin gluten o tamari',
    'Jugo de limón y semillas de sésamo',
  ],
  'instructions': [
    'Cocinar el arroz y reservar.',
    'Saltear el pollo con salsa tamari hasta dorar.',
    'Montar todo en un bowl: arroz, pollo y verduras.',
    'Aliñar con limón y sésamo.',
  ],
  'nutrition': {
    'protein': '32g',
    'carbs': '40g',
    'fat': '20g',
    'fiber': '5g',
  },
},
{
  'name': 'Guiso de Lentejas y Verduras',
  'calories': '380 por porción',
  'time': '35 min',
  'image': 'https://cdn.pixabay.com/photo/2016/10/27/22/52/lentil-1776614_1280.jpg',
  'difficulty': 'Fácil',
  'types': ['Meal prep', 'Almuerzos', 'Vegano'],
  'ingredients': [
    '1 taza de lentejas cocidas',
    '1/2 cebolla',
    '1 zanahoria picada',
    '1/2 taza de zapallo',
    'Condimentos: cúrcuma, pimentón, sal y ajo',
    '1 cdita de aceite de oliva',
  ],
  'instructions': [
    'Sofreír cebolla y zanahoria con aceite.',
    'Agregar lentejas y zapallo con agua suficiente.',
    'Cocinar a fuego bajo 20-25 min hasta espesar.',
    'Guardar en potes individuales para la semana.',
  ],
  'nutrition': {
    'protein': '20g',
    'carbs': '50g',
    'fat': '8g',
    'fiber': '13g',
  },
},
{
  'name': 'Panqueques de Avena y Banana',
  'calories': '290',
  'time': '15 min',
  'image': 'https://cdn.pixabay.com/photo/2017/06/02/18/24/pancakes-2361544_1280.jpg',
  'difficulty': 'Fácil',
  'types': ['Desayunos', 'Sin azúcar'],
  'ingredients': [
    '1 banana madura',
    '1 huevo',
    '1/3 taza de avena molida',
    '1 cdita de canela',
    'Aceite en spray para cocinar',
  ],
  'instructions': [
    'Triturar la banana y mezclar con el huevo y la avena.',
    'Agregar canela al gusto.',
    'Cocinar en sartén antiadherente 2-3 min por lado.',
    'Servir con frutillas o yogur natural si se desea.',
  ],
  'nutrition': {
    'protein': '9g',
    'carbs': '35g',
    'fat': '10g',
    'fiber': '5g',
  },
},
{
  'name': 'Salteado de Pollo con Batata y Brócoli',
  'calories': '550',
  'time': '30 min',
  'image': 'https://cdn.pixabay.com/photo/2023/04/20/11/06/chicken-7939591_1280.jpg',
  'difficulty': 'Media',
  'types': ['Almuerzos', 'Fitness'],
  'ingredients': [
    '150g de pechuga de pollo',
    '1 batata mediana en cubos',
    '1 taza de brócoli cocido',
    '1 cdita de aceite de oliva',
    'Condimentos: cúrcuma, orégano, pimienta, sal',
  ],
  'instructions': [
    'Hervir o asar la batata hasta ablandar.',
    'Cocinar el pollo en sartén con aceite y condimentos.',
    'Añadir el brócoli y batata, y saltear 3-4 minutos.',
  ],
  'nutrition': {
    'protein': '40g',
    'carbs': '40g',
    'fat': '20g',
    'fiber': '8g',
  },
},
{
  'name': 'Smoothie Verde Detox Energético',
  'calories': '180',
  'time': '5 min',
  'image': 'https://cdn.pixabay.com/photo/2015/08/13/14/20/smoothie-887352_1280.jpg',
  'difficulty': 'Fácil',
  'types': ['Bebidas', 'Detox'],
  'ingredients': [
    '1 taza de espinaca',
    '1/2 manzana verde',
    '1/2 plátano',
    '1 cdita de jengibre fresco rallado',
    '1/2 taza de agua o agua de coco',
    'Hielo (opcional)',
  ],
  'instructions': [
    'Colocar todos los ingredientes en la licuadora.',
    'Procesar hasta obtener una mezcla suave.',
    'Beber al instante para mayor efecto.',
  ],
  'nutrition': {
    'protein': '2g',
    'carbs': '25g',
    'fat': '1g',
    'fiber': '4g',
  },
},

];

Future<void> migrateRecipesToFirestore() async {
  final firestore = FirebaseFirestore.instance;
  final batch = firestore.batch();
  final recipesCollection = firestore.collection('recipes');

  for (final recipe in localRecipes) {
    final docRef = recipesCollection.doc();
    batch.set(docRef, recipe);
  }
  await batch.commit();
  debugPrint('Recetas migradas a Firestore correctamente.');
}

/// Para ejecutar la migración, llama a migrateRecipesToFirestore() desde un botón o initState temporalmente.
