// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    } 
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFP_9Ux-oL4UdqrTb8QsuJTEgnPgkqNjg',
    appId: '1:208818262116:web:e5c36a98f9a892208d8f71',
    messagingSenderId: '208818262116',
    projectId: 'fitria-122db',
    authDomain: 'fitria-122db.firebaseapp.com',
    storageBucket: 'fitria-122db.firebasestorage.app',
    measurementId: 'G-67F5F2ETHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBko9HMwwkbYVA5ntZaiL78Bi-hJpM_fbM',
    appId: '1:208818262116:android:4cd82584186a36b08d8f71',
    messagingSenderId: '208818262116',
    projectId: 'fitria-122db',
    storageBucket: 'fitria-122db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfzsd5YH04krVfV0K4ttWmGLwT8vd3ZOU',
    appId: '1:208818262116:ios:eb535bad492463648d8f71',
    messagingSenderId: '208818262116',
    projectId: 'fitria-122db',
    storageBucket: 'fitria-122db.firebasestorage.app',
    iosBundleId: 'com.example.fitria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfzsd5YH04krVfV0K4ttWmGLwT8vd3ZOU',
    appId: '1:208818262116:ios:eb535bad492463648d8f71',
    messagingSenderId: '208818262116',
    projectId: 'fitria-122db',
    storageBucket: 'fitria-122db.firebasestorage.app',
    iosBundleId: 'com.example.fitria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFP_9Ux-oL4UdqrTb8QsuJTEgnPgkqNjg',
    appId: '1:208818262116:web:b4b120e713ca52e28d8f71',
    messagingSenderId: '208818262116',
    projectId: 'fitria-122db',
    authDomain: 'fitria-122db.firebaseapp.com',
    storageBucket: 'fitria-122db.firebasestorage.app',
    measurementId: 'G-N6B1D9K5CJ',
  );

}